### ISSUE TITLE
I am not able to run localturk (ubuntu 14.10)

### ISSUE THREAD

**Issue by vijaymanikandan** [danvk/localturk#13]
I followed this link from your writeup on "Training an Ocropus OCR model". You have done a great job in explaining the details! I tried using your localturk but it doesn't seem to work for me. I am using ubuntu 14.10. When I run it, I get "/usr/bin/env: node: No such file or directory". Do you know why this might happen?

**Comment by danvk** [comment]
You need to install node :)

**Comment by vijaymanikandan** [comment]
Thanks for the very quick response. I am not an expert in this so googled how to install node for ubuntu. I tried running "sudo apt-get install nodejs" and it says requirement satisfied. I guess it is installed but somehow it is not seen by localturk? When I installed localturk following your instructions, I saw it installed in /usr/local/lib/node_modules/localturk/. Am I doing something wrong?

**Comment by vijaymanikandan** [comment]
OK I think I found a fix (from https://github.com/nodejs/node-v0.x-archive/issues/3911)

I guess my node binary is called nodejs. So I did "ln -s /usr/bin/nodejs /usr/bin/node" and now when I run localturk, It opened up a browser page for me to label the images (I don't see the images though). But I guess I can work from here. I will keep you posted. Thanks!!
