### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by slifty** [danvk/localturk#16]
I'd like to adapt some of this for use in a project at the Internet Archive.  I am not seeing any license information in this repository, is it under Apache 2.0 or MIT by any chance?

**Comment by danvk** [comment]
Good catch. Which would you prefer?

**Comment by slifty** [comment]
No strong preference on my end!  Maybe Apache 2?  Thanks!

**Comment by danvk** [comment]
@slifty do you need an NPM release with this?

**Comment by slifty** [comment]
No this is all set on my end thank you!
