### ISSUE TITLE
install failure on LinuxMint/Ubuntu

### ISSUE THREAD

**Issue by bugsyb** [danvk/localturk#22]
Hi Dan,

Many thanks for great tool - localturk.
Trying to install it on LinuxMint v18.2 (Sonya) with "sudo npm install localturk -g" I'm getting following error:
```
david@DP55L ~/OCR/localturk $ sudo npm install localturk -g
npm ERR! path /usr/local/lib/node_modules/localturk/dist/localturk.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/localturk/dist/localturk.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
```

And log shows:
```
...
1698 verbose stack Error: ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/localturk/dist/localturk.js'
1699 verbose cwd /home/user/
1700 verbose Linux 4.10.0-40-generic
1701 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "install" "localturk" "-g"
1702 verbose node v9.2.1
1703 verbose npm  v5.6.0
1704 error path /usr/local/lib/node_modules/localturk/dist/localturk.js
1705 error code ENOENT
1706 error errno -2
1707 error syscall chmod
1708 error enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/localturk/dist/localturk.js'
1709 error enoent This is related to npm not being able to find a file.
1710 verbose exit [ -2, true ]

```
I've tried creating localturk under node_modules folder without luck. Tried that but trust it should be automatically created.

**Comment by bugsyb** [comment]
ok, found issue.
When running npm install localturk -g one has to be in the folder within which "localturk" and below folders as synced from git are.

**Comment by danvk** [comment]
You should be able to install `localturk` from anywhere, so this is definitely a bug. Thanks for the heads up!

**Comment by danvk** [comment]
This should be fixed with the 2.0.3 release. If you can verify by installing from outside the `localturk` directory, that'd be much appreciated.

Thanks again for the heads up. (Also curious how you discovered localturk!)

**Comment by bugsyb** [comment]
How did I find localturk? 
Working on small private project around OCR & training, came across your great article:
http://www.danvk.org/2015/01/11/training-an-ocropus-ocr-model.html

I find locaturk written in very smart way - like it very much.
In fact if I can, will submit a small RFE.

Trying to re-install localturk (workedaround by removing localturk and classify-images from /usr/local/bin/
###
/usr/local/bin/localturk -> /usr/local/lib/node_modules/localturk/dist/localturk.js
npm ERR! path /usr/local/bin/classify-images
npm ERR! code EEXIST
npm ERR! Refusing to delete /usr/local/bin/classify-images: ../lib/node_modules/localturk/classify-images.js symlink target is not controlled by npm /usr/local/bin
npm ERR! File exists: /usr/local/bin/classify-images
npm ERR! Move it away, and try again.
###

Other than that worked like a charm below is run from within /usr/local/bin
/usr/local/bin $ sudo npm install -g localturk
/usr/local/bin/localturk -> /usr/local/lib/node_modules/localturk/dist/localturk.js
/usr/local/bin/classify-images -> /usr/local/lib/node_modules/localturk/dist/classify-images.js
+ localturk@2.0.3
added 64 packages in 5.889s

**Comment by speculaas** [comment]
Dear All,
Thanks for your help!

Hope you dont mind this quick question before I dive into this repo:
Have you try running localturk on a LAN?

I discovered it via Google.
I was looking for simple way to crowd sourcing training set collection.
The following are my google search keyword leading me here : (reversed chronological order)

&q=mechanical+turk+implementation+github&

&q=mechanical+turk+versus%2C+DIY+web+server&
&q=mechanical+turk+versus%2C+implement+web+server&
&q=mechanical+turk+like%2C+implement+web+server&
&q=mechanical+turk%2C+implement+web+server&
?q=mechanical+turk&

&q=crowdsourcing+implementation%2C+web+server+to+label+data%2C+stackoverflow&
&q=crowdsourcing+implementation+suggestion%2C+web+server+to+label+data%2C+stackoverflow&
&q=web+server+to+label+data%2C+stackoverflow&
?q=php+to+take+survey&

BR,
Jimmy

**Comment by speculaas** [comment]
Dear All, 

Thanks for your help!
After updating nodejs version(ps.1), I found it works on LAN without needing any modification, config, etc.

And then I encountered my first problem in localturk:

Error: Error: Number of columns is inconsistent on line 2
    at /usr/local/lib/node_modules/localturk/dist/csv.js:117:31
    at step (/usr/local/lib/node_modules/localturk/dist/csv.js:32:23)
    at Object.next (/usr/local/lib/node_modules/localturk/dist/csv.js:13:53)
    at resume (/usr/local/lib/node_modules/localturk/dist/csv.js:43:44)
    at fulfill (/usr/local/lib/node_modules/localturk/dist/csv.js:45:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

BR,
Jimmy




ps.1,
/usr/local/lib/node_modules/localturk/node_modules/csv-parse/lib/index.js:114
Parser = function(options = {}) {
                          ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/localturk/dist/csv.js:55:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by JensHumrich** [comment]
@speculaas This issue arises in case your csv file contains commas and the parsing of tasks.csv fails.
