### ISSUE TITLE
RFE: allow OCRed suggestions

### ISSUE THREAD

**Issue by bugsyb** [danvk/localturk#23]
Not really sure how to title it properly, but idea is more or less, that as part of training, it might be worth to have capability that job input would contain also OCRed text based on currently available model.

This would be extremely helpful in case of updating model and long texts, where existing model would be making just small mistakes.
Instead of retyping full text it might be way easier to check it visually and correct prior submit.
One more check box in such scenario would be required. 

This check box would be by default un-checked.
Typing anything in the text box (including any changes should box be pre-filled with OCRed text) would automatically tick the checkbox.
Should no changes be made in the textbox (i.e. it would contain correctly recognized text) it would be required to manually tick the checkbox, confirming text has been correctly recognized and reviewed. This is to avoid situation where "turk" would by accident submit mistakenly reviewed text (or due to laziness).

This is extremely helpful in case of repeating lines of text, i.e. training Ocropus on different fonts.

I can see pros and cons for the approach as it can lead to some mistakes but overall value seem to be very good.

Hopefully I'm not over-complicating anything.

Thanks for help if possible.

**Comment by bugsyb** [comment]
Further tests didn't lead to final solution, but probably a simple change would allow this.

Creating tasks.csv with:
```
input1,line1
./0001/010001.bin.png,abc
./0001/010002.bin.png,def

```

and template with:
```
<style>
input{font-size: x-large;}
</style>

<img src="${input1}" /><br>
<input type="text" name="line1" size=60 value=${line1} /><br>

```

Gives almost expected results.

The only problem is that in this case it is now raising error and storing incorrect data in output.csv
HTML for first task is generated correctly (has correct "value") but when submit it generates incorrect output to be stored and returns back to first line.

```
Running local turk on http://localhost:4321
{ input1: './0001/010001.bin.png', line1: 'abc' }
Saved {"input1":"./0001/010001.bin.png","line1":["abc","changed_abc_to_this"]}
{ input1: './0001/010001.bin.png', line1: 'abc' }

```
Note that the original value was "abc" and modified prior submission to "changed_abc_to_this".
This is then stored as separate columns and localturk returns to first line again.

This is more a bug now than a RFE, hence as opening as new issue as bug and closing original RFE.

**Comment by danvk** [comment]
Just use a different name for the input & output fields, i.e.

    <input type="text" name="output-line" size=60 value=${input-line} /><br>

**Comment by bugsyb** [comment]
Many thanks - it does the job.
It even saves the suggested (input-line) as well as submit output-line. This is great as allows to run also stats on errors.
Example output:
```
input1,iline1,output1
./0001/010001.bin.png,abc,1manual
./0001/010002.bin.png,def,2manual
./0001/010003.bin.png,ghi,3manual
```

Thanks again!
