### ISSUE TITLE
line value in template for input processed incorrectly

### ISSUE THREAD

**Issue by bugsyb** [danvk/localturk#25]
The requirement is to read filename and default value for text input from tasks file.

Creating tasks.csv with:
```
input1,line1
./0001/010001.bin.png,abc
./0001/010002.bin.png,def

```

and template with:
```
<style>
input{font-size: x-large;}
</style>

<img src="${input1}" /><br>
<input type="text" name="line1" size=60 value=${line1} /><br>

```

Gives almost expected results.

Error is raised:
`1 / 4 No new keys in output. Make sure your <input> elements have "name" attributes`

Incorrect data is stored in output.csv
HTML for first task is generated correctly (has correct "value") but when submit it generates incorrect output to be stored and returns back to first line. Counter is incremented but looped and never gets to next item.

```
Running local turk on http://localhost:4321
{ input1: './0001/010001.bin.png', line1: 'abc' }
Saved {"input1":"./0001/010001.bin.png","line1":["abc","changed_abc_to_this"]}
{ input1: './0001/010001.bin.png', line1: 'abc' }

```
Note that the original value was "abc" and modified prior submission to "changed_abc_to_this".
This is then stored as separate columns and localturk returns to first line again.

This is more a bug now than a RFE, hence as opening as new issue as bug and closing original RFE.

**Comment by danvk** [comment]
This is WAI. Just like Mechanical Turk, localturk uses the input values to figure out which tasks have been completed. See #23.
