### ISSUE TITLE
Question: does localturk save partial progress?

### ISSUE THREAD

**Issue by NQNStudios** [danvk/localturk#31]
I'm just wondering if I have a really large dataset (and I do), will it be possible to partially annotate it using localturk, but saving the output.csv file, and later run it again to annotate more data and expand the existing training set without starting over?

**Comment by danvk** [comment]
Yes.

To decide which task to serve, localturk reads your input and output files and looks for inputs which aren't fully contained in the output. So it should resume jobs just fine. You should see this in the progress indicator (MM/NNNN tasks complete).

**Comment by NQNStudios** [comment]
Great, thanks.
