### ISSUE TITLE
No access to the localturk server. 

### ISSUE THREAD

**Issue by chrisa530** [danvk/localturk#33]
![image](https://user-images.githubusercontent.com/60558439/97129406-3cfe8f80-1715-11eb-81ba-edb0707a742f.png)
![image](https://user-images.githubusercontent.com/60558439/97129438-4c7dd880-1715-11eb-9345-786b6186b3e7.png)

**Comment by danvk** [comment]
Should be `cd localturk\sample` (Backslash) on Windows.

**Comment by chrisa530** [comment]
Thank you for replying. The localhost blocks the connection. This is the error that I keep getting

![image](https://user-images.githubusercontent.com/60558439/97326972-e8f5c700-184a-11eb-98bd-1293c2f01f0e.png)

**Comment by danvk** [comment]
It's likely that this was an issue with the CSV file ("Error: Number of columns is inconsistent on line 2").
